### ISSUE TITLE
Nodes with NodePath type argument and node selector

### ISSUE THREAD

**Issue by NullMember** [Vahera/godot-orchestrator#118]
### Describe the bug

In the Orchestrator, when a node with a NodePath type argument is created and the "Assign" button is pressed, the node selector displays a node tree of the currently open scene, allowing the user to select any node within that scene. However, the node searches the selected node relative to itself, rather than relative to the root of the currently open scene. This behavior leads to a "node not found" error.

### Expected behavior

Selected node should be found

### Actual behavior

Selected node not found

### How to Reproduce?

1. Crate scene with node tree like this
```
RootNode
|
|-- OrchestratorNode (Attached Orchestrator script)
|
|-- OtherNode
```
2. Open scene
3. Add "Call Get Node" node to Orchestrator script
4. Press Assign button and select OtherNode
5. Run project

### Godot full version

4.2.1

### Orchestrator version

2.0.dev3

**Comment by Naros** [comment]
I've always found this process to be quite problematic for a variety of reasons.

In the old Godot 3 implementation, it made an assumption that you were not attaching the same script to multiple nodes and that it would build the `NodePath` relative to the first scene node that had the script attached.  I had hoped to avoid this problem by trying to keep things relative to the edited scene root, using making the path explicitly based on `/root/...` can be equally problematic for instantiated scenes within scenes.

I'll need to look into this more to see if this is a way forward that works for all cases.  This seems to also be a problem by dragging a node onto the canvas to generate a `SceneNode` instance in the top level scene; however, the same process works inside a nested, instantiated scene. :(

**Comment by Naros** [comment]
One other thing I noticed is that for nested scenes, it appears that our default value handler exposes the child nodes in the dialog popup, whereas the default editor behavior does not.  This should also likely change and be aligned with the editor's behavior.

**Comment by NullMember** [comment]
If an ideal solution isn't found, perhaps a single checkbox could let the user select either a root-based or OScript-attached scene path. I don't have a perfect solution yet. I'm still familiarizing myself with the Orchestrator codebase and can't contribute quality PRs at this time. However, if you have any ideas, I'm willing to try implementing them if you're short on time.

**Comment by Naros** [comment]
No worries @NullMember.  

Looking more into this, I see a way forward.  For `Get Scene Node` nodes, these need to be root-based.  This is primarily because Godot's built-in scene node selector enforces root-based node paths, and there is no way to influence that behavior.  However, I noticed something that we may want to guard against but I'm not yet sure how, open to suggestions.

Let's say we have two scenes:
```
+ MainScene
  + SomeChild
    + SomeGrandChild (scriptA attached)
  + NestedScene
```
```
+ NestedScene
  + AnotherChild
    + AnotherGrandChild (scriptB attached)
```
These two scenes are open in two editor tabs, and within the Orchestrator main view, both `scriptA` and `scriptB` are open.  Now, it is technically possible for a user to drag a node from `MainScene` into `scriptB` but in this case since `scriptB` is not attached with any node in the main scene, the lookup will fail.

We probably should have some type of validation here, but I'm not yet sure exactly based on what.
