### ISSUE TITLE
Select node and easy move them to a function

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#156]
### Description

The graph will get big kinda fast. You can move nodes to function and call them from the main script.

### Implementation ideas

Be able to select nodes and right click or in some way create a new function with the nodes we have selected. Create the new function and have the chain uninterupted in the graph. If there are function argument and return values these should be created as well.

**Comment by Naros** [comment]
Hi @GhostNr1, this is something we are certainly wanting to support.  

We have been looking at how we intend to design macros and function libraries, and we wanted to be sure that it was thoroughly flushed out before we decided to implement collapsing and expanding between different graph types.  This ensures that whatever behavior we implement for this works universally across the various spectrums of graphs so that the refactor toggling is seamless.

We believe we have a solid foundation for how we intend to do macros and functions, so we should be able to start work on this soon.

**Comment by GhostNr1** [comment]
Yea, the foundation is very solid. It is a breeze to work with it.
