### ISSUE TITLE
Can't drag scene to variable with any

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#163]
### Describe the bug

If you create a new variable and have it set to any and you try to drag and drop a scene from filesystem you get a no drop icon pointer and can't drop it

### Expected behavior

If there are any you should be able to drop anything to that slot

### How to Reproduce?

1. Create a new variable
2. Select type Any on the variable
3. Export the variable so you see it on the node
4. Select the node you have the script
5. Drag and drop a scene to the exported variable

### Godot full version

4.2.1.stable

### Orchestrator version

v2.0.rc1

**Comment by Naros** [comment]
Looking at this from the lens of GDScript, this is the restriction on exported variables:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/2ea114f0-9169-4e5f-a677-84f34d6301c6)

This circles back to something I've wanted to change, and that was how variables and their respective types are defined anyway.  Right now, a lot of our code is based solely on `Variant::Type`, and we'd like to extend this so that it's just more than the specific enum value.

For example in UE they have something like this:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/601b094a-8a14-4fae-9ce6-1eb0aaaa8e12)

We should remove the `Any` classification for variables entirely and when selecting the `Object` type, you would then need to pick a base object type to represent the exported variable.  The user would also be able to select `Enum` and then they would need to pick the specific enum type to confine the variable to.

**Comment by Naros** [comment]
Additionally, it does not make sense that `Callable`, `RID`, or `Signal` are exported variable types either as the fields cannot be modified in the Inspector.

**Comment by GhostNr1** [comment]
I agree to all of this. That should also solve if you have own defined classes that can be selected

**Comment by Naros** [comment]
Fixed by #302
