### ISSUE TITLE
Add_child not working as intendent

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#179]
### Describe the bug

When adding a node in the tree with add_child it's not giving a random number as described in the documentation https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-add-child instead it allways use the force_readable_name. Then you can only add one node then it will have a conflict in naming. Reflected in the documentation is also that if two siblings collide in naming a number should be added to avoid conflicts

### How to Reproduce?

1. Create one scene with some nodes
2. Create another scene with a script
3. In a loop (use timer to not get to many created at a time) then instansiate the first scene and then call add_child
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/1d9c12ae-efad-4b5a-b8b6-a19b255612d3)

### Godot full version

4.2.1.stable

### Orchestrator version

v2.0.rc1.official [551ed1f73]

**Comment by GhostNr1** [comment]
I was trying it out with gdscript to see how it behave and if nothing it should not use nice name it look like this when you run.

![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/92a455aa-e5b3-4fca-bd02-7e58dc7346c8)

It just create a new node with @<typeOfScene>@<Id> And if you use readble name it look like this instead
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/d67f4b97-7292-44dd-8077-fa81541cca9f)

I also tried if I could use callv and use add_child but I get the same result as the add_child node

**Comment by Naros** [comment]
Hi @GhostNr1 so I think this is working, the issue is you've attached the `Instantiate Scene` output to the wrong input port.  I suspect if you take a look in your debug window, you should see an error that says:
```
E 0:00:00:0842   add_child: Parameter "p_child" is null.
  <C++ Source>   scene/main/node.cpp:1486 @ add_child()
```
In this case, we should see whether we can exclude the _Target_ node from being auto-wired.  The `target` in this case is the current node the script is attached to, but it exists to allow nodes to manipulate the tree of other nodes.
