### ISSUE TITLE
Variable nodes?

### ISSUE THREAD

**Issue by gvrocksnow** [Vahera/godot-orchestrator#18]
Would variable nodes (bool, String, Vector3, Node3D etc) be added in the future?
Also would be cool if we can optionally assign those from the scene tree for the relevant nodes.

**Comment by Naros** [comment]
Variable nodes are definitely on the roadmap.

One idea I have is to introduce a new Variables node type, and this node allows you to define the name & type of the node and add it to a list.  Once the variable is defined, you can either set the value by manually adjusting the assignment or by dragging a value onto the row from the scene node, which would be useful for things like `Node3D`.

A mock-up is as follows:
```
+--------------------------------------------------------------+
| Variables                                                [X] |
+--------------------------------------------------------------+
| [+] Name: [                            ] Type: [ Boolean v ] |
|                                                              |
| my_var                    = [                          ] [X] |
| my_node                   = [/root/.../MyNode3D        ] [X] |
+--------------------------------------------------------------+
```

Then inside the `Expression` and `Condition` nodes, you could reference the variable directly by it's name and it would reference the actual value defined in the Variables node.  

Another idea I am considering is whether it makes sense to define Variables similar to Godot's old Visual Scripting system where it's actually baked into the Editor UI and you access the values using a `Variable` node that acts as a reference:

A mock-up is as follows:
```
+---------------+
| Variable  [X] |
+---------------+
| my_var        |
|   value (str) o
+---------------+
```

But in this situation, it would completely change how at least `Condition` would work.  Rather than you defining the condition as a line of code, we'd need to start introducing operators to build the condition as a node graph and then pass that sub-graph as an input into the Condition node to evaluate if its output is true or false.  

The main concern with the latter approach is that it begins to take Orchestrator down a very, very low-level style of design and based on feedback we got before we embarked on this plug-in, it goes against what we heard.

A final idea is to mix the two styles together.  There isn't a proper "Variable" node implementation at all, but instead, the variables are defined as part of the Orchestrator Editor UI.  These can be defined by dragging nodes from the scene tree into the Variables list or by adding a variable manually and assigning its type & value.  Once they're defined, they're used just like in the first idea.  The only difference here is the node is baked into the Editor UI rather than an actual node in the graph.

Any suggestions or preferences on style @gvrocksnow ?

**Comment by gvrocksnow** [comment]
Just checked if the graph can access Autoload variables and it works already, so never mind about the global variables part.

**Comment by Naros** [comment]
Hi @gvrocksnow so with the just released Orchestrator [v2.0.dev1](https://github.com/Vahera/godot-orchestrator/releases/tag/v2.0.dev1), you can now use variables as well as _local stack-based variables_ within user-defined functions.

I am curious whether Godot registers Autoloads as Singletons or whether those are seen differently.  If they're seen differently and aren't explicitly registered as "Singleton" objects from `Engine::get_singleton_list()` point of view, then we likely should consider adding a specialized node to access autoloads or extend the current singleton node to also return references to anything that is currently an autoload.  

What's your thoughts?

**Comment by gvrocksnow** [comment]
I haven't used Godot that extensively, so I'm not sure I can help you here.

**Comment by Naros** [comment]
Autoload behavior superseded by #136 and https://github.com/Vahera/godot-orchestrator/pull/137
