### ISSUE TITLE
Same behavior when selecting a scene and selecting a script

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#207]
### Description

If you have GDScript and you have script attached to the root node and you select that scene then the script will be selected if you are in the script editor. It would be benificial if the same behavior is in Orchestrator.

**Comment by Naros** [comment]
Hi @GhostNr1, so if I understand, you have a `.gd` script attached to the root scene node, and when selecting that scene the script is selected if within the script editor.  I tested this on 4.3.dev4 and v4.2.1-stable, and I don't see this behavior.

If you click the `Script` icon on a scene node, the script opens in the script editor if it's a `.gd` script.  This works with Orchestrator, too, but if you're using any 4.3 dev build before 4.3.dev4, this behavior was broken due to a change in the editor that caused a regression. This should work just fine on Godot 4.3.dev4 or later.

If you're referring to something else, if you could elaborate on the steps a bit more, that'd help.

**Comment by GhostNr1** [comment]
https://github.com/Vahera/godot-orchestrator/assets/9337875/66e7cb42-caea-4759-9a69-a993c215746b

Here is a video what is happening in gdscript and what is not happening in orchestrator. I would like to have the same behavior.

**Comment by Naros** [comment]
OK, I think that's reason 👍
