### ISSUE TITLE
Dictionary 'find key' and 'get' do not have output nodes

### ISSUE THREAD

**Issue by gstroudharris** [Vahera/godot-orchestrator#289]
### Describe the bug

Referenced in the following bug report: https://discord.com/channels/1049457206648655912/1226553132578897920

There are no output nodes for two of the main ways to get information from/about dictionaries.
![image](https://github.com/Vahera/godot-orchestrator/assets/15918543/6f83e878-f70b-4043-b700-2d48ac58b976)

### Expected behavior

1. User creates a "Find Key" or "Get" dictionary node.
2. Node has an 'output' nodule, letting us get information about the dictionary input.

### Actual behavior

1. User creates a "Find Key" or "Get" dictionary node.
2. Node has no output except for the continuation nodule.

### How to Reproduce?

0. Create a new project with Orchestrator 2.1.
1. Create a scene and attach an Orchestrator script.
2. Create a dictionary.
3. Create a string to search that dictionary with.
4. Create a 'Find Key' or 'Get' dictionary node
5. Observe that the node does not have an output nodule.

### Godot full version

v4.2.1.stable.mono.official [b09f793f5]

### Orchestrator version

Orchestrator 2.1 
![image](https://github.com/Vahera/godot-orchestrator/assets/15918543/5aa1eb87-2c58-4c0e-acc8-07420429f64d)

**Comment by Naros** [comment]
This was similar to GH-240, but the root cause was different.  

In this case, we parse the `extension_api.json` file to create a C++ class called `ExtensionDB` and we misinterpreted the meaning of `"return_type": "Variant"` and the method data that was being generated did not include the `PROPERTY_USAGE_NIL_AS_VARIANT` flag, hence why no return values showed up.

This ended up affecting the following Godot functions:

* PackedByteArray.decode_var
* Array.get_typed_script
* Array.min
* Array.max
* Array.reduce
* Array.pop_at
* Array.pop_front
* Array.pop_back
* Array.pick_random
* Array.back
* Array.front
* Dictionary.get
* Dictionary.find_key
* Callable.call
* Callable.callv
* AABB.intersects_ray
* AABB.intersects_segment
* Plane.intersects_ray
* Plane.intersects_segment
* Plane.intersect_3
