### ISSUE TITLE
Unable to add new variables to an orchestration if any variable is added to a Category

### ISSUE THREAD

**Issue by tarragonfly** [Vahera/godot-orchestrator#89]
### Describe the bug

If any existing variable is added to a Category, I'm unable to add new variables. Once the categorized variable is deleted, I can add variables again. 

### Expected behavior

By clicking the + button, I should be able to add variables no matter what categories are configured.

### Actual behavior

Can't add new variables if a Category is defined for some variable.

### How to Reproduce?

1. Add new variable of any type
2. Add that variable to "abc" Category
3. Try to add a new variable and notice that it's not possible anymore

### Godot full version

4.2.1

### Orchestrator version

2.0.dev2

**Comment by Naros** [comment]
Hi @tarragonfly can you confirm if you are leaving the variable names their default of `NewVar`?  If so, that would explain the behavior as variable names are unique, regardless of their grouping.  The category grouping works much in the same way as GDScript where you cannot have the same variable name used more than once per script.

That said, I thought we had code in place to append a `_####` sequence so that adding new list entries that had the same default name would have this suffix appended to handle allowing multiple variables and then renaming them after-the-fact.  I'll look into this and report back.

**Comment by Naros** [comment]
> That said, I thought we had code in place to append a `_####` sequence so that adding new list entries that had the same default name would have this suffix appended to handle allowing multiple variables and then renaming them after-the-fact. I'll look into this and report back.

So, looking at the code, the issue is specifically with variables and categories.  The collection of child names in the list does not take into account the new category hierarchy, and that is what results in the suffix logic not working.  I will have a fix shortly 👍 .
